# Verify the Polkadot call at           https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.polkadot.io#/extrinsics/decode
# Verify the Darwinia2 call at https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.darwinia.network#/extrinsics/decode
[darwinia]
	[darwinia.asset-hub]
	accept         = "0x210001010002140004000000000700e40b540213000000000700e40b54020006000700f2052a01183c01e8030000140d010004000100f91f"
	accept-result  = ""
	batch          = ""
	batch-result   = ""
	request        = ""
	request-result = ""

	[darwinia.astar]
	accept         = "0x210001010002140004000000000700e40b540213000000000700e40b54020006000700f2052a01183c01d6070000140d010004000100f91f"
	accept-result  = "https://darwinia2.subsquare.io/council/motions/10"
	batch          = ""
	batch-result   = ""
	request        = "0x0d0001010002140004000000000700e40b540213000000000700e40b540200060002286bee383c00d6070000e803000000900100140d010004000100f91f"
	request-result = "on darwinia-1.0"

	[darwinia.bifrost]
	accept         = ""
	accept-result  = ""
	batch          = "0x1000080d0001010002140004000000000700e40b540213000000000700e40b540200060002286bee383c00ee070000e803000000900100140d010004000100f91f0d0001010002140004000000000700e40b540213000000000700e40b540200060002286bee183c01ee070000140d010004000100f91f"
	batch-result   = "on darwinia-1.0"
	request        = ""
	request-result = ""

	[darwinia.moonbeam]
	accept         = "0x0d0001010002140004000000000700e40b540213000000000700e40b540200060002286bee183c01d4070000140d010004000100f91f"
	accept-result  = "on darwinia-1.0"
	batch          = ""
	batch-result   = ""
	request        = ""
	request-result = ""

	[darwinia.parallel]
	accept         = ""
	accept-result  = ""
	batch          = ""
	batch-result   = "on darwinia-1.0"
	request        = ""
	request-result = ""

	[darwinia.phala]
	accept         = ""
	accept-result  = ""
	batch          = "0x1000080d0001010002140004000000000700e40b540213000000000700e40b540200060002286bee383c00f3070000e803000000900100140d010004000100f91f0d0001010002140004000000000700e40b540213000000000700e40b540200060002286bee183c01f3070000140d010004000100f91f"
	batch-result   = "on darwinia-1.0"
	request        = ""
	request-result = ""

	[darwinia.polkadex]
	accept         = ""
	accept-result  = ""
	batch          = "0x1a0008210001010002140004000000000700e40b540213000000000700e40b54020006000700f2052a01183c01f8070000140d010004000100f91f210001010002140004000000000700e40b540213000000000700e40b54020006000700f2052a01383c00f8070000e803000000900100140d010004000100f91f"
	batch-result   = "https://darwinia2.subsquare.io/council/motions/11"
	request        = ""
	request-result = ""

	[darwinia.statemint]
	accept         = ""
	accept-result  = ""
	batch          = ""
	batch-result   = ""
	request        = "0x0d0001010002140004000000000700e40b540213000000000700e40b540200060002286bee383c00e8030000e803000000900100140d010004000100f91f"
	request-result = "on darwinia-1.0"

# Verify the Kusama call at         https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-rpc.polkadot.io#/extrinsics/decode
# Verify the Crab2 call at https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fcrab-rpc.darwinia.network%2F#/extrinsics/decode
[crab]
	[crab.bifrost]
	accept         = ""
	accept-result  = ""
	batch          = "0x1000080d000101000210000400000000070010a5d4e81300000000070010a5d4e80006000700f2052a01383c00dc070000e8030000009001000d010004000100e5200d000101000210000400000000070010a5d4e81300000000070010a5d4e80006000700f2052a01183c01dc0700000d010004000100e520"
	batch-result   = "on darwinia-1.0"
	request        = ""
	request-result = ""

	[crab.crust]
	accept         = ""
	accept-result  = ""
	batch          = "0x1000080d000101000210000400000000070010a5d4e81300000000070010a5d4e80006000700f2052a01383c00dc070000e8030000009001000d010004000100e5200d000101000210000400000000070010a5d4e81300000000070010a5d4e80006000700f2052a01183c01dc0700000d010004000100e520"
	batch-result   = "on darwinia-1.0"
	request        = ""
	request-result = ""

	[crab.khala]
	accept         = ""
	accept-result  = ""
	batch          = "0x1000080d000101000210000400000000070010a5d4e81300000000070010a5d4e80006000700f2052a01383c00d4070000e8030000009001000d010004000100e5200d000101000210000400000000070010a5d4e81300000000070010a5d4e80006000700f2052a01183c01d40700000d010004000100e520"
	batch-result   = "on darwinia-1.0"
	request        = ""
	request-result = ""

	[crab.karura]
	accept         = ""
	accept-result  = "on darwinia-1.0"
	batch          = ""
	batch-result   = ""
	request        = ""
	request-result = "on darwinia-1.0"

	[crab.litmus]
	accept         = ""
	accept-result  = ""
	batch          = "0x1000080d000101000214000400000000070010a5d4e81300000000070010a5d4e80006000700f2052a01383c003a080000e803000000900100140d010004000100e5200d000101000214000400000000070010a5d4e81300000000070010a5d4e80006000700f2052a01183c013a080000140d010004000100e520"
	batch-result   = "on darwinia-1.0"
	request        = ""
	request-result = ""

	[crab.moonriver]
	accept         = ""
	accept-result  = "on darwinia-1.0"
	batch          = ""
	batch-result   = ""
	request        = ""
	request-result = "on darwinia-1.0"

	[crab.parallel]
	accept         = ""
	accept-result  = ""
	batch          = "0x1000080d000101000214000400000000070010a5d4e81300000000070010a5d4e80006000700f2052a01383c0025080000e803000000900100140d010004000100e5200d000101000214000400000000070010a5d4e81300000000070010a5d4e80006000700f2052a01183c0125080000140d010004000100e520"
	batch-result   = "on darwinia-1.0"
	request        = ""
	request-result = ""

	[crab.shiden]
	accept         = "0x21000101000214000400000000070010a5d4e81300000000070010a5d4e800060002286bee183c01d7070000140d010004000100e520"
	accept-result  = "https://crab.subscan.io/referenda/0"
	batch          = ""
	batch-result   = ""
	request        = "0x0d000101000214000400000000070010a5d4e81300000000070010a5d4e80006000700f2052a01383c00d7070000e803000000900100140d010004000100e520"
	request-result = "on darwinia-1.0"

# Verify the Rococo call at             https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-rpc.polkadot.io#/extrinsics/decode
# Verify the Pangolin2 call at https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpangolin-rpc.darwinia.network#/extrinsics/decode
[pangolin]
	[pangolin.rocstar]
	accept         = "0x21000101000214000400000000070010a5d4e81300000000070010a5d4e800060002286bee183c01d6070000140d010004000100e520"
	accept-result  = "https://pangolin.subscan.io/block/574452"
	batch          = ""
	batch-result   = ""
	request        = "0x21000101000214000400000000070010a5d4e81300000000070010a5d4e800060002286bee383c00d6070000e803000000900100140d010004000100e520"
	request-result = "https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpangolin-rpc.darwinia.network#/explorer/query/0xc4c94f9cdf9d98c62e21b21c18d23e197a505a8f430e9c7cb209554648764315"
